
const constants = {
  UPDATE_SEARCH_FIELDS: 'registrationList/UPDATE_SEARCH_FIELDS',
  UPDATE_REGISTRATIONS: 'registrationList/USER_SEARCH_UPDATE_REGISTRATIONS',
  TOGGLE_SEARCH_TYPE: 'registrationList/USER_SEARCH_TOGGLE_SEARCH_TYPE',
  FETCHING: 'registrationList/FETCHING',
  FETCH_COMPLETE: 'registrationList/FETCH_COMPLETE',
  UPDATE_TABLE_PROPS: 'registrationList/UPDATE_TABLE_PROPS',
  SET_ACTIVE_USER: 'registrationList/SET_ACTIVE_USER',
  SET_ACTIVE_REQUEST: 'registrationList/SET_ACTIVE_REQUEST',
  SET_MODAL_VISIBLE: 'registrationList/SET_MODAL_VISIBLE',
  TOGGLE_SUCCESS_MESSAGE_VISIBILTY: 'registrationList/TOGGLE_SUCCESS_MESSAGE_VISIBILTY',
}

export default constants
